# Generated by Django 4.1.7 on 2023-09-15 07:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, null=True, verbose_name='配置项')),
                ('value', models.CharField(max_length=24, null=True, verbose_name='配置值')),
            ],
        ),
        migrations.CreateModel(
            name='QualityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=4, null=True, verbose_name='属性唯一定位')),
                ('label', models.CharField(max_length=32, null=True, verbose_name='属性中文标签')),
                ('maxThreshold', models.CharField(max_length=16, null=True, verbose_name='属性最大阈值')),
                ('minThreshold', models.CharField(max_length=16, null=True, verbose_name='属性最小阈值')),
                ('unit', models.CharField(max_length=16, null=True, verbose_name='属性单位')),
                ('maxOrigin', models.CharField(max_length=16, null=True, verbose_name='标准化前最大值')),
                ('minOrigin', models.CharField(max_length=16, null=True, verbose_name='标准化前最小值')),
                ('model', models.FileField(max_length=64, null=True, upload_to=app.models.QualityItem.getmodelUploadPath, verbose_name='属性所用模型')),
                ('dataURL', models.CharField(max_length=64, null=True, verbose_name='属性所在表格地址')),
                ('dataColumn', models.IntegerField(null=True, verbose_name='属性所在表格列数')),
                ('inputDim', models.IntegerField(null=True, verbose_name='属性输入维度')),
                ('outputDim', models.IntegerField(null=True, verbose_name='属性预测长度')),
                ('onPredicting', models.BooleanField(default=False, max_length=8, verbose_name='该属性数据正在执行更改')),
                ('onWorking', models.BooleanField(default=False, max_length=8, verbose_name='本属性所有工作模块已可用')),
                ('data', models.TextField(null=True, verbose_name='输出数据，长度为inputDim+outputDim')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32, verbose_name='注册码')),
                ('serialadmin', models.BooleanField(default=True, max_length=16, verbose_name='注册码类型')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('avatar', models.ImageField(default='/src/images/users/default.png', upload_to='users', verbose_name='头像')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('useradmin', models.BooleanField(default=True, max_length=16, verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('model_cnn', models.FileField(null=True, upload_to=app.models.getmodelPathCNN, verbose_name='模型')),
                ('model_crnn', models.FileField(null=True, upload_to=app.models.getmodelPathCRNN, verbose_name='CRNN模型')),
                ('model_lstm', models.FileField(null=True, upload_to=app.models.getmodelPathLSTM, verbose_name='LSTM模型')),
                ('model_temp', models.FileField(null=True, upload_to=app.models.getmodelPathTemp, verbose_name='待识别模型')),
            ],
        ),
    ]
