# Generated by Django 4.1.7 on 2023-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityitem',
            name='dataURL',
        ),
    ]
