# Generated by Django 4.1 on 2023-10-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_qualityitem_dataurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login',
            field=models.BooleanField(default=False, verbose_name='登录状态'),
        ),
    ]
