# Generated by Django 4.1.7 on 2024-01-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityitem',
            name='nodeType',
            field=models.CharField(max_length=64, null=True, verbose_name='指标在知识图谱中对应的类别名称'),
        ),
        migrations.AlterField(
            model_name='qualityitem',
            name='label',
            field=models.CharField(max_length=64, null=True, verbose_name='属性中文标签'),
        ),
    ]
