# Generated by Django 4.1.7 on 2024-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_qualityitem_graphleft_qualityitem_graphright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/src/images/users/default.jpeg', upload_to='users', verbose_name='头像'),
        ),
    ]
