# Generated by Django 4.1.7 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityitem',
            name='isBinary',
            field=models.BooleanField(default=False, max_length=8, verbose_name='指标是否是二元相'),
        ),
    ]
